/*
 *
 * Projects constants
 *
 */

export const FETCH_PROJECTS_REQUEST = 'app/Projects/FETCH_PROJECTS_REQUEST'
export const FETCH_PROJECTS_SUCCESS = 'app/Projects/FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAILURE = 'app/Projects/FETCH_PROJECTS_FAILURE'

export const ADD_PROJECT_REQUEST = 'app/Projects/ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'app/Projects/ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAILURE = 'app/Projects/ADD_PROJECT_FAILURE'

export const DELETE_PROJECT_REQUEST = 'app/Projects/DELETE_PROJECT_REQUEST'
export const DELETE_PROJECT_SUCCESS = 'app/Projects/DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'app/Projects/DELETE_PROJECT_FAILURE'